import React from 'react';
// footer was generated by ai
export default function Footer() {
  return (
    <footer className="w-full bg-white border-t border-purple-100/80 mt-32 pt-16 pb-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        
        {/* Top Grid Section */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
          
          {/* Brand/Logo Area */}
          <div className="md:col-span-1">
            <div className="flex items-center gap-2 text-purple-900 font-extrabold text-xl tracking-tight mb-4">
              <div className="bg-purple-600 text-white p-2 rounded-xl shadow-md shadow-purple-200">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
                </svg>
              </div>
              <span>ShortURL</span>
            </div>
            <p className="text-sm text-purple-400 font-medium leading-relaxed">
              Simplifying link management with premium speed, dynamic metrics, and personalized barcode access.
            </p>
          </div>

          {/* Links Column 1 */}
          <div>
            <h4 className="text-purple-950 font-bold text-sm tracking-wide uppercase mb-4">Product</h4>
            <ul className="space-y-2.5 text-sm font-semibold text-purple-400">
              <li><a href="#features" className="hover:text-purple-700 transition-colors">Features</a></li>
              <li><a href="#pricing" className="hover:text-purple-700 transition-colors">Pricing</a></li>
              <li><a href="/dashboard" className="hover:text-purple-700 transition-colors">Analytics</a></li>
            </ul>
          </div>

          {/* Links Column 2 */}
          <div>
            <h4 className="text-purple-950 font-bold text-sm tracking-wide uppercase mb-4">Legal</h4>
            <ul className="space-y-2.5 text-sm font-semibold text-purple-400">
              <li><a href="#privacy" className="hover:text-purple-700 transition-colors">Privacy Policy</a></li>
              <li><a href="#terms" className="hover:text-purple-700 transition-colors">Terms of Service</a></li>
              <li><a href="#cookies" className="hover:text-purple-700 transition-colors">Cookie Settings</a></li>
            </ul>
          </div>

          {/* Newsletter / Action Section */}
          <div>
            <h4 className="text-purple-950 font-bold text-sm tracking-wide uppercase mb-4">Stay Updated</h4>
            <p className="text-xs text-purple-400 font-medium mb-3">Get tips on optimizing your link CTR parameters.</p>
            <div className="flex bg-purple-50/50 rounded-xl border border-purple-100/50 p-1 focus-within:ring-2 focus-within:ring-purple-400/30 transition-all">
              <input 
                type="email" 
                placeholder="Enter email" 
                className="w-full bg-transparent px-3 py-1.5 text-xs text-purple-900 font-medium focus:outline-none placeholder-purple-300"
              />
              <button className="bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs px-3 py-1.5 rounded-lg shadow-sm transition-all active:scale-95 whitespace-nowrap cursor-pointer">
                Join
              </button>
            </div>
          </div>

        </div>

        {/* Bottom Copyright Section */}
        <div className="border-t border-purple-50 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs font-semibold text-purple-300">
            &copy; {new Date().getFullYear()} ShortURL Inc. All rights reserved.
          </p>
          
          {/* Social Icons matching your branding color way */}
          <div className="flex items-center gap-4">
            <a href="#twitter" className="text-purple-300 hover:text-purple-600 transition-colors">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
            </a>
            <a href="#github" className="text-purple-300 hover:text-purple-600 transition-colors">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.166 6.839 9.489.5.092.682-.217.682-.48 text-0-.197-.007-.72-.011-1.412-2.782.603-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.464-1.11-1.464-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.831.092-.646.35-1.086.636-1.336-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.025 2.747-1.025.546 1.377.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.578.688.479C19.138 20.162 22 16.418 22 12c0-5.523-4.477-10-10-10z"/></svg>
            </a>
          </div>
        </div>

      </div>
    </footer>
  );
}
